
//various endpoints and id's used with multiple tests
var props = {};
props.credAccessToken = '1234567abcdef';
props.accessToken = 'thisisnotanaccesstoken';
props.storeTemplateId = '123456';
props.orderId = '34543';
props.fulfillmentId = '858640';
props.productId = '485343';
props.variantId = '9938495';
props.collectionId = '456322256';
props.shippingGroupId = '6544859';
props.shippingClassId = '188734';
props.webhookId = '666';
props.clientId = '854204212853';
props.secret = 'FS8333FCVNO';
props.callback = function() { return 23; };
props.rootApiUrl = 'https://api.storenvy.com';
props.userInfoUrl = 'https://api.storenvy.com/v1/me.json?access_token=';
props.storeInfoUrl = 'https://api.storenvy.com/v1/store.json?access_token=';
props.createStoreUrl = 'https://api.storenvy.com/v1/stores?access_token=';
props.updateStoreUrl = 'https://api.storenvy.com/v1/store?access_token=';
props.getStoreVisitsUrl = 'https://api.storenvy.com/v1/store/visits.json?access_token=';
props.getStoreMarketplaceVisitsUrl = 'https://api.storenvy.com/v1/store/marketplace_visits.json?access_token=';
props.getStoreTemplatesUrl = 'https://api.storenvy.com/v1/store/templates.json?access_token=';
props.updateStoreTemplateUrl = 'https://api.storenvy.com/v1/store/templates/' + props.storeTemplateId + '?access_token=';
props.createStoreTemplateUrl = 'https://api.storenvy.com/v1/store/templates?access_token=';
props.getOrdersUrl = 'https://api.storenvy.com/v1/orders.json?access_token=';
props.getOrderUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '.json?access_token=';
props.shipOrderUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '/ship?access_token=';
props.holdOrderUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '/hold?access_token=';
props.openOrderUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '/open?access_token=';
props.getOrderProductsUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '/products.json?access_token=';
props.getOrderVariantsUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '/variants.json?access_token=';
props.updateFulfillmentUrl = 'https://api.storenvy.com/v1/orders/' + props.orderId + '/fulfillments/' + props.fulfillmentId + '?access_token=';
props.getProductsUrl = 'https://api.storenvy.com/v1/products.json?access_token=';
props.getProductUrl = 'https://api.storenvy.com/v1/products/' + props.productId + '.json?access_token=';
props.createProductUrl = 'https://api.storenvy.com/v1/products?access_token=';
props.updateProductUrl = 'https://api.storenvy.com/v1/products/' + props.productId + '?access_token=';
props.createVariantUrl = 'https://api.storenvy.com/v1/products/' + props.productId + '/variants?access_token=';
props.getVariantUrl = 'https://api.storenvy.com/v1/products/' + props.productId + '/variants/' + props.variantId + '.json?access_token=';
props.updateVariantUrl = 'https://api.storenvy.com/v1/products/' + props.productId + '/variants/' + props.variantId + '?access_token=';
props.getCollectionsUrl = 'https://api.storenvy.com/v1/collections.json?access_token=';
props.getCollectionUrl = 'https://api.storenvy.com/v1/collections/' + props.collectionId + '.json?access_token=';
props.createCollectionUrl = 'https://api.storenvy.com/v1/collections?access_token=';
props.updateCollectionUrl = 'https://api.storenvy.com/v1/collections/' + props.collectionId + '?access_token=';
props.getShippingGroupsUrl = 'https://api.storenvy.com/v1/shipping_groups.json?access_token=';
props.getShippingGroupUrl = 'https://api.storenvy.com/v1/shipping_groups/' + props.shippingGroupId + '.json?access_token=';
props.createShippingGroupUrl = 'https://api.storenvy.com/v1/shipping_groups?access_token=';
props.updateShippingGroupUrl = 'https://api.storenvy.com/v1/shipping_groups/' + props.shippingGroupId + '?access_token=';
props.getShippingClassesUrl = 'https://api.storenvy.com/v1/shipping_classes.json?access_token=';
props.getShippingClassUrl = 'https://api.storenvy.com/v1/shipping_classes/' + props.shippingClassId + '.json?access_token=';
props.createShippingClassUrl = 'https://api.storenvy.com/v1/shipping_classes?access_token=';
props.updateShippingClassUrl = 'https://api.storenvy.com/v1/shipping_classes/' + props.shippingClassId + '?access_token=';
props.getShippingRateUrl = 'https://api.storenvy.com/v1/shipping_rate.json?access_token=';
props.updateShippingRateUrl = 'https://api.storenvy.com/v1/shipping_rate?access_token=';
props.getWebhooksUrl = 'https://api.storenvy.com/v1/webhooks.json?access_token=';
props.getWebhookUrl = 'https://api.storenvy.com/v1/webhooks/' + props.webhookId + '.json?access_token=';
props.createWebhookUrl = 'https://api.storenvy.com/v1/webhooks?access_token=';
props.updateWebhookUrl = 'https://api.storenvy.com/v1/webhooks/' + props.webhookId + '?access_token=';
props.createAccountUrl = 'https://api.storenvy.com/v1/application/stores?access_token=';
props.subdomain = 'meatcube';
props.path = 'myPath.json';
props.page = '3';
props.perPage = '10';
props.basicUrl = 'http://' + props.subdomain + '.storenvy.com/' + props.path;
props.getStoreInfoUrl = 'http://' + props.subdomain + '.storenvy.com/store.json';
props.publicGetProductsUrl = 'http://' + props.subdomain + '.storenvy.com/products.json';
props.publicGetProductUrl = 'http://' + props.subdomain + '.storenvy.com/products/' + props.productId + '.json';
props.publicGetCollectionsUrl = 'http://' + props.subdomain + '.storenvy.com/collections.json';
props.publicGetCollectionUrl = 'http://' + props.subdomain + '.storenvy.com/collections/' + props.collectionId + '.json';
props.appId = 'UAA992303KMP';
props.appSecret = 'FJ498F91030U0';
props.redirect = 'http://meatcube.com';
props.OauthUrl = 'https://www.storenvy.com/oauth/authorize?client_id=' + props.appId +
   '&response_type=code' + '&redirect_uri=' + props.redirect + '&scope=user';
props.accessToken = 'UU8894iJjkfd998';
props.refreshToken = '89FUIS8336F';
props.expiresIn = 1000;

module.exports = props;